var e = {
    1001: "发现栏小程序主入口",
    1005: "顶部搜索框的搜索结果页",
    1006: "发现栏小程序主入口搜索框的搜索结果页",
    1007: "单人聊天会话中的小程序消息卡片",
    1008: "群聊会话中的小程序消息卡片",
    1011: "扫描二维码",
    1012: "长按图片识别二维码",
    1013: "手机相册选取二维码",
    1014: "小程序模版消息",
    1017: "前往体验版的入口页",
    1019: "微信钱包",
    1020: "公众号 profile 页相关小程序列表",
    1022: "聊天顶部置顶小程序入口",
    1023: "安卓系统桌面图标",
    1024: "小程序 profile 页",
    1025: "扫描一维码",
    1026: "附近小程序列表",
    1027: "顶部搜索框搜索结果页 之使用过的小程序列表",
    1028: "我的卡包",
    1029: "卡券详情页",
    1030: "自动化测试下打开小程序",
    1031: "长按图片识别一维码",
    1032: "手机相册选取一维码",
    1034: "微信支付完成页",
    1035: "公众号自定义菜单",
    1036: "App 分享消息卡片",
    1037: "小程序打开小程序",
    1038: "从另一个小程序返回",
    1039: "摇电视",
    1042: "添加好友搜索框的搜索结果页",
    1043: "公众号模板消息",
    1044: "带 shareTicket 的小程序消息卡片",
    1045: "朋友圈广告",
    1047: "扫描小程序码",
    1048: "长按图片识别小程序码",
    1049: "手机相册选取小程序码",
    1052: "卡券的适用门店列表",
    1053: "搜一搜的结果页",
    1054: "顶部搜索框小程序快捷入口",
    1056: "音乐播放器菜单",
    1057: "钱包中的银行卡详情页",
    1058: "公众号文章",
    1059: "体验版小程序绑定邀请页",
    1064: "微信连Wi-Fi状态栏",
    1067: "公众号文章广告",
    1068: "附近小程序列表广告",
    1069: "移动应用",
    1071: "钱包中的银行卡列表页",
    1072: "二维码收款页面",
    1073: "客服消息列表下发的小程序消息卡片",
    1074: "公众号会话下发的小程序消息卡片",
    1077: "摇周边",
    1078: "连Wi-Fi成功页",
    1079: "微信游戏中心",
    1081: "客服消息下发的文字链",
    1082: "公众号回话下发的文字链",
    1089: "微信聊天主界面下拉",
    1090: "长按小程序右上角菜单唤出最近使用历史",
    1091: "公众号文章商品卡片",
    1092: "城市服务入口",
    1095: "小程序广告组件",
    1096: "聊天记录",
    1097: "微信支付签约页"
}, a = {
    "pages/index/index": "小程序首页",
    "pages/category/category": "类型、品牌、型号查询页面",
    "pages/detail/detail": "询价页面",
    "pages/inquiry/inquiry": "询价结果页面",
    "pages/inquiry/choose-shop": "询价结果选择店面页面",
    "pages/inquiry/choose-city": "询价结果选择城市页面",
    "pages/ondoormap/ondoormap": "询价修改上门地址页面",
    "pages/maihuishou/maihuishou": "老版个人中心页面",
    "pages/activity/friendAssistance/friendAssistance": "加价活动页面",
    "pages/activity/public/public": "邀新活动页面容器",
    "pages/inquiry/servies": "服务条款页面",
    "pages/order/order": "订单提交成功页面",
    "pages/activity/coupon/coupon": "优惠券领取页面",
    "pages/inquiry/get-phone-failed": "获取手机号失败页面",
    "pages/order/help/check-order": "订单相关帮助信息页面",
    "pages/order/help/backup-tutorial": "备份相关帮助信息页面",
    "pages/order/help/unlock-tutorial": "账号密码解锁教程帮助页面",
    "pages/m_ahs/checkorder/checkorder": "查看订单相关信息页面",
    "pages/scancode/scancode": "小程序扫描二维码页面",
    "pages/activity/template/template": "活动的容器页面（助力/梭梭树）",
    "pages/usercenter/index": "新版个人中心页面首页",
    "pages/usercenter/login": "个人中心页面登录页",
    "pages/activity/private/private": "需要身份的活动的容器页面（订单/钱包/帮助中心/邀新有礼..后面还会增加)",
    "pages/inquiry/express-rule": "顺丰规则描述页面",
    "pages/nosku/nosku": "商品为无sku商品时",
    "pages/reservation/index": "预约门店流程选择门店页",
    "pages/reservation/confirm": "预约门店流程确认信息页",
    "pages/reservation/success": "预约门店流程提交成功页",
    "pages/reservation/map": "预约门店推送模板打开地图页"
};

module.exports = {
    pointData: e,
    objInfoMap: a
};