var e = "https://i.meituan.com/brunch/applet/", i = "https://apimobile.meituan.com/group";

module.exports = {
    indexApi: e + "index",
    dealApi: e + "deal",
    postOrderApi: "https://i.meituan.com/weixin/deal/buy",
    postOrderApiDaozong: "https://web.meituan.com/web/wxbuy/daozong",
    errReportApi: e + "err",
    captchaApi: "https://i.meituan.com/account/appcaptcha",
    poiApi: "https://apimobile.meituan.com/group/v1/poi/",
    poiDealApi: "https://apimobile.meituan.com/group/v1/deal/poi/",
    loginApi: e + "user/login",
    uuidApi: e + "user/uuid",
    mobileCodeApi: e + "user/mobilecode",
    mobileCodeCheckApi: e + "user/mobilecodecheck",
    foodOrderDetailApi: "https://i.meituan.com/weixin/order/",
    yuleOrderDetailApi: "https://i.meituan.com/general/platform/mtusercenter/mtorder.json",
    poiListApi: e + "deal-pois",
    orderListApi: "https://ordercenter.meituan.com/ordercenter/user/orders",
    reviewPayApi: e + "review-pay",
    reviewTagApi: e + "review-tag",
    reviewApi: e + "review",
    lxApi: "https://report.meituan.com/lx-report",
    getCityInfoByLocApi: "https://i.meituan.com/locate/latlng/",
    swiper: {
        indicatorDots: !0,
        autoplay: !0,
        current: 0,
        interval: 5e3,
        duration: 1e3
    },
    toastConf: {
        duration: 2e3,
        text: "默认",
        hidden: !0,
        handler: "toastHandler"
    },
    getOpenId: "https://i.meituan.com/wrapapi/getopenid",
    userInfoApi: "https://i.meituan.com/wrapapi/getLoginedUserInfo",
    guessApi: i + "/v2/recommend/homepage/city/",
    commentsApi: "https://web.meituan.com/web/poi/",
    commentsDealApi: "https://web.meituan.com/web/deal/",
    poiAlunmApi: "https://web.meituan.com/web/album/poi/",
    commentScoreApi: "https://web.meituan.com/web/poi/",
    commentPoiTagsApi: "https://web.meituan.com/web/poi/",
    commentDealTagsApi: "https://web.meituan.com/web/deal/",
    votegoodApi: "https://web.meituan.com/web/comment/",
    nearsApi: i + "/v2/recommend/nearstoredeals/poi/",
    recommendApi: i + "/v2/deal/recommend/collaborative",
    branchApi: "https://i.meituan.com/brunch/applet/deal-pois",
    couponApi: "https://mapi.dianping.com/pay/generalpromo/v1/getgeneralpromodeskcoupon.jsonp",
    foodOrderVoucherApi: "https://rpc.meituan.com/api/foodorder",
    c_zcApi: "https://c-zc.meituan.com/api/wxapp/coupon",
    yuleMerchantVouchersApi: "https://mapi.dianping.com/pay/promo/issuecouponcomponent.json",
    getYuleMerchantVouchersApi: "https://mapi.dianping.com/pay/promo/issuecoupon.json",
    vouchersApi: i + "/v6/user/",
    TICKET_APPID: "wx4fa555703dced95c",
    WAIMAI_APPID: "wx2c348cf579062e56",
    TRAIN_APPID: "wx7970573ccad929a7",
    ZHENGGUO_APPID: "wxc147016e2b3bf9d6",
    MT_APPID: "wxde8ac0a21135c07d",
    YUEFAN_APPID: "wx539d7a6b4552424b"
};