module.exports = {
    index: "/pages/index/index",
    play: "/pages/play/index",
    channel: "/pages/channel/index",
    search: "/pages/search/index",
    user: "/pages/user/index",
    searchlist: "/pages/searchlist/index",
    history: "/pages/history/index",
    playlist: "/pages/playlist/index",
    list: "/pages/list/index",
    label: "/pages/label/index",
    vip: "/pages/vip/index",
    vipflow: "/pages/vip/flow/index",
    egg: "/pages/egg/index",
    star: "/pages/star/index",
    "star-detail": "/pages/star/subpages/detail/index",
    "star-work": "/pages/star/subpages/work/index",
    settings: "/pages/settings/index",
    hot: "/pages/hot/index",
    tag: "/pages/hot/tag",
    vplus: "/pages/hot/vplus",
    live: "/pages/live/index"
};