Object.defineProperty(exports, "__esModule", {
    value: !0
});

var s = [ {
    name: "限时秒杀",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/xsms78.png_1527488340669",
    pageSrc: "time_spike",
    url: "/pages/spike/spike",
    redPoint: !1,
    newGif: !0,
    hitTimes: 1
}, {
    name: "品牌清仓",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/ppqc78.png_1527488455401",
    pageSrc: "super_spike",
    url: "/pages/subjects/subjects?subjects_id=14",
    redPoint: !0,
    newGif: !1,
    hitTimes: 1
}, {
    name: "食品超市",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/spcs78.png_1527488758076",
    pageSrc: "food",
    url: "/pages/subjects/subjects?subjects_id=17",
    redPoint: !1,
    newGif: !1,
    hitTimes: 1
}, {
    name: "时尚穿搭",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/sscd78.png_1527488823042",
    pageSrc: "fashion_dress",
    url: "/pages/subjects/subjects?subjects_id=22",
    redPoint: !1,
    newGif: !1,
    hitTimes: 1
}, {
    name: "海淘",
    hitTimes: 0,
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/ht78.png_1527488971506",
    newGif: !1,
    pageSrc: "haitao_code",
    redPoint: !1,
    url: "/pages/haitao/haitao"
}, {
    name: "9块9特卖",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/99tm78.png_1527489126590",
    pageSrc: "bargain",
    url: "/pages/subjects/subjects?subjects_id=12",
    redPoint: !1,
    newGif: !1,
    hitTimes: 1
}, {
    name: "爱逛街",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/aigj78.png_1527494052877",
    pageSrc: "go_shopping",
    url: "/pages/subjects/subjects?subjects_id=15",
    redPoint: !1,
    newGif: !1,
    hitTimes: 1
}, {
    name: "名品折扣",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/mpzk78.png_1527489310154",
    pageSrc: "economical_brand",
    url: "/pages/subjects/subjects?subjects_id=21",
    redPoint: !1,
    newGif: !1,
    hitTimes: 1
}, {
    name: "手机充值",
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/sjcz78.png_1527489387033",
    pageSrc: "charge_center",
    url: "/pages/subjects/subjects?subjects_id=19",
    redPoint: !0,
    newGif: !1,
    hitTimes: 1
}, {
    hitTimes: 1,
    img: "http://minipinduoduo.oss-cn-shanghai.aliyuncs.com/oms/index/ttlxj78.png_1527489519710",
    name: "我的订单",
    newGif: !1,
    pageSrc: "orders",
    redPoint: !1,
    url: "/package_a/orders/orders?type=0",
    version: "v1.5.6"
} ];

exports.default = s;