Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.KEYS = exports.Message = void 0;

var E = new (function(E) {
    return E && E.__esModule ? E : {
        default: E
    };
}(require("./pubsub")).default)(), _ = {
    PAGE_MAIN_REQUEST_FINISHED: "PAGE_MAIN_REQUEST_FINISHED",
    TRACKING_FROM_REQUEST: "TRACKING_FROM_REQUEST",
    MONITOR_FROM_REQUEST: "MONITOR_FROM_REQUEST",
    REQUEST_NEED_LOGIN: "REQUEST_NEED_LOGIN",
    SOCKET_OPEN: "SOCKET_OPEN",
    SOCKET_ERROR: "SOCKET_ERROR",
    SOCKET_CLOSED: "SOCKET_CLOSED",
    AUTH_OK: "AUTH_OK",
    AUTH_FAIL: "AUTH_FAIL",
    UNREAD_MESSAGE_COUNT: "UNREAD_MESSAGE_COUNT",
    STORAGE_FAIL: "STORAGE_FAIL",
    BUBBLE_MESSAGE: "BUBBLE_MESSAGE",
    CUSTOM_SERVICE_MESSAGE: "CUSTOM_SERVICE_MESSAGE",
    RECONNECT_ERROR: "RECONNECT_ERROR",
    WAIT_FOR_SPIKE_SHOW: "WAIT_FOR_SPIKE_SHOW",
    ORDERCHECKOUT_CHOOSE_ADDRESS: "ORDERCHECKOUT_CHOOSE_ADDRESS",
    LOCAL_MANAGE_ORDERS: "LOCAL_MANAGE_ORDERS",
    AUTO_CREATE_ORDER_CHECKOUT_PAY: "AUTO_CREATE_ORDER_CHECKOUT_PAY",
    ORDER_CHECKOUT_PAY: "ORDER_CHECKOUT_PAY",
    REQUEST_TOKEN_INVALID: "REQUEST_TOKEN_INVALID",
    USER_LOGIN_FINISHED: "USER_LOGIN_FINISHED",
    NO_ORDER_USER_CHECK_FINISHED: "NO_ORDER_USER_CHECK_FINISHED",
    UNDEFINED_EVENT_TYPE: "UNDEFINED_EVENT_TYPE",
    TRACEING_GROUP_INFO: "TRACEING_GROUP_INFO",
    GROUP_SIGN_IN_FROM_SHARE_CARD: "GROUP_SIGN_IN_FROM_SHARE_CARD",
    GROUP_SIGN_IN_FROM_SHARE_BTN: "GROUP_SIGN_IN_FROM_SHARE_BTN",
    RED_ENVELOPE_HELP_FROM_SHARE_BTN: "RED_ENVELOPE_HELP_FROM_SHARE_BTN",
    RED_ENVELOPE_HELP_FROM_SHARE_CARD: "RED_ENVELOPE_HELP_FROM_SHARE_CARD",
    GOLDEN_EGGS_CHOOSE_ADDRESS: "GOLDEN_EGGS_CHOOSE_ADDRESS"
};

exports.Message = E, exports.KEYS = _;