module.exports = {
    cate: [ {
        url: "/pages/cate-list/cate-list?cateCode=4&cateId=574",
        catecode: "4",
        name: "全职招聘",
        iconclass: "qzzp"
    }, {
        url: "/pages/list/list?cateCode=5&dispCateId=13941&cateId=577",
        catecode: "5",
        name: "兼职",
        iconclass: "jz"
    }, {
        url: "/pages/list/list?cateCode=1&dispCateId=8&cateId=8",
        catecode: "1",
        name: "整租",
        iconclass: "zz"
    }, {
        url: "/pages/list/list?cateCode=2&dispCateId=10&cateId=10",
        catecode: "2",
        name: "合租",
        iconclass: "hz"
    }, {
        url: "/pages/list/list?cateCode=3&dispCateId=12&cateId=12",
        catecode: "3",
        name: "二手房",
        iconclass: "mf"
    }, {
        url: "/pages/cate-list/cate-list?cateCode=10",
        catecode: "10",
        name: "二手物品",
        iconclass: "eswp"
    }, {
        url: "/pages/list/list?cateCode=6&dispCateId=13978&cateId=29",
        catecode: "6",
        name: "二手车",
        iconclass: "esc"
    }, {
        url: "/pages/cate-list/cate-list?cateCode=8",
        catecode: "8",
        name: "本地服务",
        iconclass: "bdfw"
    }, {
        url: "/pages/list/list?cateId=2626&dispCateId=9546&cateIdParent=580&cateCode=4&type=near&parentDispCateId=13901",
        catecode: "11",
        name: "附近工作",
        iconclass: "fjgz"
    }, {
        url: "/pages/list/list?cateId=31&dispCateId=31&cateCode=8",
        catecode: "12",
        name: "拼车",
        iconclass: "pc"
    } ],
    tools: [ {
        url: "/pages/operators/job/job",
        name: "行业薪资",
        iconclass: "hyxz"
    }, {
        url: "/pages/web-view-list/ordinary/index?url=https%3A%2F%2Fplatform.58.com%2Fcalc%2Findex",
        name: "工资计算器",
        iconclass: "gzjsq"
    }, {
        url: "/pages/service-seek/service-seek",
        name: "意向登记",
        iconclass: "yxdj"
    }, {
        url: "/pages/wenda/question/question",
        name: "问答",
        iconclass: "wd"
    }, {
        url: "/pages/friend/friend",
        name: "默契匹配",
        iconclass: "mqpp"
    } ]
};