Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.default = {
    channels: [ {
        cid: "RE_MEN",
        cname: "热门"
    }, {
        cid: "GAO_XIAO",
        cname: "搞笑"
    }, {
        cid: "ZONG_YI",
        cname: "综艺"
    }, {
        cid: "ZI_XUN",
        cname: "资讯"
    } ],
    resultChannels: [ {
        cid: "DIAN_YING",
        cname: "电影"
    }, {
        cid: "ZONG_YI",
        cname: "参加综艺"
    }, {
        cid: "YIN_YUE",
        cname: "音乐"
    }, {
        cid: "DIAN_SHI_JU",
        cname: "电视剧"
    } ],
    channelMap: {
        RE_MEN: 0,
        DIAN_YING: 1,
        DIAN_SHI_JU: 2,
        JI_LU_PIAN: 3,
        DONG_MAN: 4,
        YIN_YUE: 5,
        ZONG_YI: 6,
        YU_LE: 7,
        GAME: 8,
        LV_YOU: 9,
        PIAN_HUA: 10,
        GONG_KAI_KE: 11,
        JIAO_YU: 12,
        SHI_SHANG: 13,
        SHI_SHANG_ZONG_YI: 14,
        SHAO_ER: 15,
        WEI_DIAN_YING: 16,
        TI_YU: 17,
        AO_YUN: 18,
        ZHI_BO: 19,
        GUANG_GAO: 20,
        SHENG_HUO: 21,
        GAO_XIAO: 22,
        QI_PA: 23,
        CAI_JING: 24,
        ZI_XUN: 25,
        QI_CHE: 26,
        YUAN_CHUANG: 27,
        TAO_MI: 91,
        LIAN_XIANG_HE_ZUO: 92,
        PIAN_MA_QI_CE_SHI: 96,
        OTHER: 97,
        CE_SHI: 99,
        VIP: 120,
        QI_YI_CHU_PIN: 111,
        PAIKE: "",
        JUNSHI: 28,
        MU_YING: 29,
        KE_JI: 30,
        TUO_KOU_XIU: 31,
        JIAN_KANG: 32,
        GONG_YI: 33
    },
    SEARCH_NUM: 12,
    TOTLE_PAGE: 21,
    maxFeedCount: 200,
    feedItemHeight: 422,
    topNavBarHeight: 100,
    feedBottomBarHeight: 112
};